### ISSUE TITLE
Could not find com.github.scottyab:rootbeer:0.08

### ISSUE THREAD

**Issue by tonydigifiv** [jeroentrappers/flutter_jailbreak_detection#10]
Hi, I'm facing an issue on building project.
Version:
**flutter_jailbreak_detection: ^1.5.0**

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.scottyab:rootbeer:0.0.8.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/scottyab/rootbeer/0.0.8/rootbeer-0.0.8.pom
       - https://jcenter.bintray.com/com/github/scottyab/rootbeer/0.0.8/rootbeer-0.0.8.pom
       - https://developer.huawei.com/repo/com/github/scottyab/rootbeer/0.0.8/rootbeer-0.0.8.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/scottyab/rootbeer/0.0.8/rootbeer-0.0.8.pom
     Required by:
         project :app > project :flutter_jailbreak_detection

**Comment by jeroentrappers** [comment]
I've update the package. Could you check again with 1.6.0. It should find the rootbeer 0.0.9 from jitpack.
