### ISSUE TITLE
M1 snippet [Feature]

### ISSUE THREAD

**Issue by oscarshaitan** [jeroentrappers/flutter_jailbreak_detection#11]
When the app is running on a M1 (directly from the stores) the Plattform detect that we are running on a iOs device and since the M1 runs the app inside an emulator, the jailbreak will detect that. should be an option to detect if we are on M1 or on a device
This could help 
Programmatically detect if iOS app is running on a Mac. -
 [https://developer.apple.com/forums/thread/656122?answerId=651150022#651150022](https://developer.apple.com/forums/thread/656122?answerId=651150022#651150022)

**Comment by jeroentrappers** [comment]
Please create a pull request upstream

Op ma 21 jun. 2021 15:49 schreef Oscar Tigreros ***@***.***>:

**Comment by oscarshaitan** [comment]
Here is the PR
[https://github.com/jeroentrappers/flutter_jailbreak_detection/pull/12](https://github.com/jeroentrappers/flutter_jailbreak_detection/pull/12)

**Comment by jeroentrappers** [comment]
Hi Oscar,

What I meant with PR upstream is to fix this potential issue in
DTTJailbreakDetection.isJailbroken().


Kind regards,

Jeroen
Op di 22 jun. 2021 21:17 schreef Oscar Tigreros ***@***.***>:

**Comment by oscarshaitan** [comment]
Yeah but this could be a solution meanwhile the DTT add this.
because this is an open issue since  Jan 13
[https://github.com/thii/DTTJailbreakDetection/issues/12](https://github.com/thii/DTTJailbreakDetection/issues/12)

**Comment by jeroentrappers** [comment]
I'm not going to change the behavior of the upstream implementations here. This library is a simple wrapper.

**Comment by Gaurav-CareMonitor** [comment]
@jeroentrappers  Any updates on this, I ma using the package but want users to use the app on Mac machines
