### ISSUE TITLE
Need to upgrade Android embedding to V2

### ISSUE THREAD

**Issue by daveols** [jeroentrappers/flutter_jailbreak_detection#14]
Flutter throws the following when building with versions greater than 2.4.0 (try with latest beta channel).

>The plugin `flutter_jailbreak_detection` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

This plugin needs to be updated use the V2 embedding method described here:

https://flutter.dev/go/android-plugin-migration

**Comment by jeroentrappers** [comment]
Should be fixed in 1.8.0. Thanks to xPutnikx
