### ISSUE TITLE
fatal error: 'flutter_jailbreak_detection/flutter_jailbreak_detection-Swift.h' file not found

### ISSUE THREAD

**Issue by ducvu212** [jeroentrappers/flutter_jailbreak_detection#15]
Error when i build app in iOS with version 1.7.0 and 1.6.0. This is flutter doctor

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-x64, locale
    en-VN)
    • Flutter version 2.2.3 at /Users/Downloads/flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/Library/Android/sdk
    • Java binary at: /Library/Internet
      Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (3 available)
    • 😘😘😘😘😘😘😘 (mobile) • 031c178e656ca6968226de750b4dd4167ddff346 • ios
      • iOS 14.6
    • macOS (desktop)         • macos                                    •
      darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)            • chrome                                   •
      web-javascript • Google Chrome 92.0.4515.159

! Doctor found issues in 1 category.

**Comment by ducvu212** [comment]
Thank you. @jeroentrappers Please proceed to merge pr 17. Tks you

**Comment by jeroentrappers** [comment]
Should be fixed in 1.8.0 thanks!
