### ISSUE TITLE
The plugin `flutter_jailbreak_detection` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by adispatil** [jeroentrappers/flutter_jailbreak_detection#18]
The plugin `flutter_jailbreak_detection` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.

**Comment by jeroentrappers** [comment]
Should be fixed in 1.8.0
