### ISSUE TITLE
 Could not find com.github.scottyab:rootbeer:0.1.0.

### ISSUE THREAD

**Issue by tonydigifiv** [jeroentrappers/flutter_jailbreak_detection#19]
Hi, I am facing issue when building the project.

**flutter_jailbreak_detection: ^1.7.0**

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.scottyab:rootbeer:0.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/scottyab/rootbeer/0.1.0/rootbeer-0.1.0.pom
       - https://jcenter.bintray.com/com/github/scottyab/rootbeer/0.1.0/rootbeer-0.1.0.pom
       - https://developer.huawei.com/repo/com/github/scottyab/rootbeer/0.1.0/rootbeer-0.1.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/scottyab/rootbeer/0.1.0/rootbeer-0.1.0.pom
     Required by:
         project :app > project :flutter_jailbreak_detection

**Comment by jeroentrappers** [comment]
Do you get the same issue when trying the example application?

**Comment by tonydigifiv** [comment]
> Do you get the same issue when trying the example application?

I have tried to run the example application, it went smoothly. Somehow it doesn't run in my project. I have tried version 1.8.0 but no luck. I even tried to update my project to the latest SDK.

**Flutter doctor**
[√] Flutter (Channel stable, 2.5.1, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Flutter version 2.5.1 at C:\Users\mcbto\Documents\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (11 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\mcbto\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.2
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\mcbto\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5556 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 93.0.961.52

• No issues found!

**Error**
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.scottyab:rootbeer:0.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/scottyab/rootbeer/0.1.0/rootbeer-0.1.0.pom
       - https://jcenter.bintray.com/com/github/scottyab/rootbeer/0.1.0/rootbeer-0.1.0.pom
       - https://developer.huawei.com/repo/com/github/scottyab/rootbeer/0.1.0/rootbeer-0.1.0.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/scottyab/rootbeer/0.1.0/rootbeer-0.1.0.pom
     Required by:
         project :app > project :flutter_jailbreak_detection

**Comment by AzaKamala** [comment]
I resolved this issue by adding `maven { url "https://jitpack.io" }` to the allprojects -> repositories in android => build.gradle.
`
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
`

**Comment by jeroentrappers** [comment]
in 1.9.0
