### ISSUE TITLE
Error in IOS 

### ISSUE THREAD

**Issue by neroaCu** [jeroentrappers/flutter_jailbreak_detection#23]
Hi,
This plugin does not work in IOS, I got the following error. Could you please take a look?

 failed for URL: "cydia://package/com.example.package" - error: "This app is not allowed to query for scheme cydia"

Flutter (Channel stable, 2.5.0, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.5.0 at /Users/xxxx/Documents/flutter2.5.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 months ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

**Comment by robinjohn** [comment]
@neroaCu , I have been getting the same error. Any resolutions found ? 

In my case, I have no other option than to remove the jailbroken check, for now, as it blocks user from using the app upon app launch.

**Comment by neroaCu** [comment]
@robinjohn 
inside the info.plist, I added the below and it works for me.

`	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>cydia</string>
	</array>`

**Comment by overdrowe** [comment]
@neroaCu Hey, so this `<key>LSApplicationQueriesSchemes</key> <array> <string>cydia</string> </array>` still works well? And this issue can be closed?

**Comment by neroaCu** [comment]
The above solution works for my case.
