### ISSUE TITLE
Detect jailbreak was wrong on mac M1

### ISSUE THREAD

**Issue by hcminh** [jeroentrappers/flutter_jailbreak_detection#24]
I have deploy my flutter app that using `flutter_jailbreak_detection` to detect jailbreak on Appstore. When I use my macbook M1 to install app it detect that my device is jailbreaked. 

Pls fix this issue :(

**Comment by jeroentrappers** [comment]
If you want to allow M1 macs, please create a PR to add this as an option. By default i don't want to allow M1 macs.
