### ISSUE TITLE
returns true even though the rooting app is only installed but the phone is not actually rooted.

### ISSUE THREAD

**Issue by abhidiwakar** [jeroentrappers/flutter_jailbreak_detection#4]
Hello @jeroentrappers 

I'm using this plugin for a personal project. During testing, I found that **this plugin returns true even if a rooting app is just installed and the device is not actually rooted**. I installed [KingRoot](https://www.apkmirror.com/apk/kingroot-studio/kingroot/kingroot-5-4-0-release/kingroot-5-4-0-android-apk-download/) to test this plugin in one of my old device which runs on Android 5.0.1.

The function that I used:
`bool jailBroken = await FlutterJailbreakDetection.jailbroken;`

Log:
```
E/RootBeer( 6294): RootBeer: isAnyPackageFromListInstalled() [249] - com.kingroot.kinguser ROOT management app detected!
E/QLog    ( 6294): RootBeer: isAnyPackageFromListInstalled() [249] - com.kingroot.kinguser ROOT management app detected!
```

**Comment by jeroentrappers** [comment]
Great! That is intended behaviour. If you want to change it, please for the plugin.

**Comment by abhidiwakar** [comment]
Wait! Are you saying that this false information is intended behavior? Look, I've tried apps like KingRoot and KingORoot which clearly shows that the device is not rooted if I've just installed a rooting app and device is not actually rooted but your plugin shows completely opposite results. Can you please explain to me why this is happening or can it be fixed somehow? I just want to achieve similar and accurate results as kingroot.

Thanks.

**Comment by jeroentrappers** [comment]
KingRoot and KingORoot are clearly intented to root a device or expand beyond it's original limitation. So it falls within what I would consider undesirable apps for my use-case.
I'm just using Rootbeer here, and I'm happy with the behavior. Open an issue over there https://github.com/scottyab/rootbeer/issues.
