### ISSUE TITLE
App crashing in rooted  real device while trying to check Device is rooted or not.

### ISSUE THREAD

**Issue by Zaveri21** [jeroentrappers/flutter_jailbreak_detection#46]
on app start i am checking iOS device is rooted or not.

```
bool isDeviceRoot = devicePlatform == "ios"
          ? await FlutterJailbreakDetection.jailbroken
          : await FlutterJailbreakDetection.developerMode;
``` 
App crashing with below error. 
-32000 Bad state: The client closed with pending request "resume".

configuration
- Flutter 3.3.9
- Dart 2.18.5
- Xcode 14.3
- Android  Dolphin
- mac os - Ventura 13.3.1 

@tvh @jeroentrappers @xPutnikx @vasilich6107 @kmoorejr9 thanks in advanced.

**Comment by vasilich6107** [comment]
I'm just a random contributor)

**Comment by Zaveri21** [comment]
> on app start i am checking iOS device is rooted or not.
> 
> ```
> bool isDeviceRoot = devicePlatform == "ios"
>           ? await FlutterJailbreakDetection.jailbroken
>           : await FlutterJailbreakDetection.developerMode;
> ```
> 
> App crashing with below error. -32000 Bad state: The client closed with pending request "resume".
> 
> configuration
> 
> * Flutter 3.3.9
> * Dart 2.18.5
> * Xcode 14.3
> * Android  Dolphin
> * mac os - Ventura 13.3.1
> 
> @tvh @jeroentrappers @xPutnikx @vasilich6107 @kmoorejr9 thanks in advanced.

After following steps i resolved issue 🚀.

```
1. flutter pub cache clean
2. flutter clean && flutter pub get
2. flutter run
```
